package bookstore.model;

import java.util.List;

public class Book {
    public static String[][] TestBookData = {
    {"p_0", "Thornton", "Classical Dynamics", "10000","marion_classicalDynamics.jpg", "This best-selling classical mechanics text, written for the advanced undergraduate one- or two-semester course, provides a complete account of the classical mechanics of particles, systems of particles, and rigid bodies. Vector calculus is used extensively to explore topics.The Lagrangian formulation of mechanics is introduced early to show its powerful problem solving ability.. Modern notation and terminology are used throughout in support of the text's objective: to facilitate students' transition to advanced physics and the mathematical formalism needed for the quantum theory of physics. CLASSICAL DYNAMICS OF PARTICLES AND SYSTEMS can easily be used for a one- or two-semester course, depending on the instructor's choice of topics.", "Professor Thornton was co-director of the IPSET(Integrated Physical Science for Elementary and Middle School Teachers) program that was supported at U.VA. by the National Science Foundation. Professor Thornton has over 100 research publications in nuclear physics and has published three college physics textbooks. He is a member of the National Science Teachers Association, the American Physical Society, the American Association for the Advancement of Science, the American Association of Physics Teachers, and the Virginia Association of Science Teachers. He helped to organize the Piedmont Regional Science Teacher's Organization(PRESTO) on which he serves as a board member."},
    {"p_1", "Griffith", "Electrodynamics", "10000","griffith_electrodynamics.jpg", "Introduction to Electrodynamics is a textbook by physicist David J. Griffiths. Generally regarded as a standard undergraduate text on the subject, it began as lecture notes that have been perfected over time. Its most recent edition, the fifth, was published in 2023 by Cambridge University Press. This book uses SI units (the mks convention) exclusively. A table for converting between SI and Gaussian units is given in Appendix C.", "David J. Griffiths received his B.A. (1964) and Ph.D. (1970) from Harvard University. He taught at Hampshire College, Mount Holyoke College, and Trinity College before joining the faculty at Reed College in 1978. In 2001-02 he was visiting Professor of Physics at the Five Colleges (University of Massachusetts, Amherst, Mount Holyoke, Smith, and Hampshire), and in the spring of 2007 he taught Electrodynamics at Stanford. He retired in 2009. Griffiths is a Consulting Editor of The American Journal of Physics, and a Fellow of the American Physical Society. In 1997 he was awarded the Millikan Medal by the American Association of Physics Teachers. He has spent sabbaticals at SLAC, Lawrence Berkeley Laboratory, and University of California, Berkeley. Although his Ph.D. was in elementary particle theory, his recent research is in electrodynamics and quantum mechanics. He is the author of over fifty articles and four books: Introduction to Electrodynamics (4th edition, Cambridge, 2013), Introduction to Elementary Particles (2nd edition, 2008), Introduction to Quantum Mechanics (2nd edition, Cambridge, 2016), and Revolutions in Twentieth-Century Physics (Cambridge, 2012)."},
    {"p_2", "Gasiorowics", "Quantum Physics", "10000","gasiorowics_quantumPhysics.jpg", "Quantum mechanics book with heavy emphasis on applications. Focuses on the physics of the applications, rather than on the mathematical structure. Order of magnitude estimates of effects are presented and calculated in detail. Nonclassical results are reconciled with classical expectations. In addition to core material, this edition contains new material on degenerate matter, the integral Quantum Hall Effect, the Einstein derivation of stimulated emission, lasers and the density matrix, exponential decay, and more. Features 60% more problems.", "Stephen George Gasiorowicz (May 10, 1928 – June 3, 2016) was an American theoretical physicist. He was born in Danzig in 1928 (Gdansk, Poland) and graduated from the University of California, Los Angeles in 1952. From 1952 until 1960, Stephen was employed by Lawrence Berkeley National Laboratory at the University of California, Berkeley, as a research staff member. In 1960 he received an offer of Associate Professorship from the Physics Department of the University of Minnesota, and in 1961 he moved to Minnesota where he stayed for the rest of his life. In 1963 he was promoted to full Professor. Gasiorowicz published over 100 papers on high-energy physics, and several well-known textbooks on the theory of elementary particles, quantum mechanics, and other subjects. Best known are Gasiorowicz’s contributions to quark models of hadrons, theory of glueballs, and QCD confinement. Gasiorowicz was one of the founding fathers of William I. Fine Theoretical Physics Institute. From 1979 to 1986 Gasiorowicz was Vice-President of the Aspen Center for Physics, Aspen, CO, and in 1987-89 the Acting Director of FTPI."},
    {"p_3", "Schroeder", "Thermal Physics", "10000","schroeder_thermalPhysics.jpg", "This text provides a balanced, well-organized treatment of thermodynamics and statistical mechanics, making thermal physics interesting and accessible to anyone who has completed a year of calculus-based introductory physics. Part I introduces essential concepts of thermodynamics and statistical mechanics from a unified view, applying concepts in a select number of illustrative examples. Parts II and III explore further applications of classical thermodynamics and statistical mechanics. Throughout, the emphasis is on real-world applications.", "Daniel V. Schroeder is a professor of physics at Wellesley College. He earned his Ph.D. in physics from Stanford University, where his research focused on theoretical studies of elementary particle physics and cosmology. After completing his doctorate, he worked as a researcher and educator at various institutions, developing expertise in computational methods and statistical mechanics. Schroeder is widely recognized for his clear and accessible teaching style, which has influenced generations of students. He is the author of An Introduction to Thermal Physics, a highly regarded textbook in the field, and co-author of Introduction to Electrodynamics: Problem Solutions Manual alongside David J. Griffiths. His academic interests include thermodynamics, statistical physics, computational simulations, and the pedagogy of physics education. Schroeder is also actively engaged in science communication and has contributed to initiatives aimed at improving undergraduate science curricula."},
    {"p_4", "Thornton", "Classical Dynamics", "10000","marion_classicalDynamics.jpg", "This best-selling classical mechanics text, written for the advanced undergraduate one- or two-semester course, provides a complete account of the classical mechanics of particles, systems of particles, and rigid bodies. Vector calculus is used extensively to explore topics.The Lagrangian formulation of mechanics is introduced early to show its powerful problem solving ability.. Modern notation and terminology are used throughout in support of the text's objective: to facilitate students' transition to advanced physics and the mathematical formalism needed for the quantum theory of physics. CLASSICAL DYNAMICS OF PARTICLES AND SYSTEMS can easily be used for a one- or two-semester course, depending on the instructor's choice of topics.", "Professor Thornton was co-director of the IPSET(Integrated Physical Science for Elementary and Middle School Teachers) program that was supported at U.VA. by the National Science Foundation. Professor Thornton has over 100 research publications in nuclear physics and has published three college physics textbooks. He is a member of the National Science Teachers Association, the American Physical Society, the American Association for the Advancement of Science, the American Association of Physics Teachers, and the Virginia Association of Science Teachers. He helped to organize the Piedmont Regional Science Teacher's Organization(PRESTO) on which he serves as a board member."},
    {"p_5", "Griffith", "Electrodynamics", "10000","griffith_electrodynamics.jpg", "Introduction to Electrodynamics is a textbook by physicist David J. Griffiths. Generally regarded as a standard undergraduate text on the subject, it began as lecture notes that have been perfected over time. Its most recent edition, the fifth, was published in 2023 by Cambridge University Press. This book uses SI units (the mks convention) exclusively. A table for converting between SI and Gaussian units is given in Appendix C.", "David J. Griffiths received his B.A. (1964) and Ph.D. (1970) from Harvard University. He taught at Hampshire College, Mount Holyoke College, and Trinity College before joining the faculty at Reed College in 1978. In 2001-02 he was visiting Professor of Physics at the Five Colleges (University of Massachusetts, Amherst, Mount Holyoke, Smith, and Hampshire), and in the spring of 2007 he taught Electrodynamics at Stanford. He retired in 2009. Griffiths is a Consulting Editor of The American Journal of Physics, and a Fellow of the American Physical Society. In 1997 he was awarded the Millikan Medal by the American Association of Physics Teachers. He has spent sabbaticals at SLAC, Lawrence Berkeley Laboratory, and University of California, Berkeley. Although his Ph.D. was in elementary particle theory, his recent research is in electrodynamics and quantum mechanics. He is the author of over fifty articles and four books: Introduction to Electrodynamics (4th edition, Cambridge, 2013), Introduction to Elementary Particles (2nd edition, 2008), Introduction to Quantum Mechanics (2nd edition, Cambridge, 2016), and Revolutions in Twentieth-Century Physics (Cambridge, 2012)."},
    {"p_6", "Gasiorowics", "Quantum Physics", "10000","gasiorowics_quantumPhysics.jpg", "Quantum mechanics book with heavy emphasis on applications. Focuses on the physics of the applications, rather than on the mathematical structure. Order of magnitude estimates of effects are presented and calculated in detail. Nonclassical results are reconciled with classical expectations. In addition to core material, this edition contains new material on degenerate matter, the integral Quantum Hall Effect, the Einstein derivation of stimulated emission, lasers and the density matrix, exponential decay, and more. Features 60% more problems.", "Stephen George Gasiorowicz (May 10, 1928 – June 3, 2016) was an American theoretical physicist. He was born in Danzig in 1928 (Gdansk, Poland) and graduated from the University of California, Los Angeles in 1952. From 1952 until 1960, Stephen was employed by Lawrence Berkeley National Laboratory at the University of California, Berkeley, as a research staff member. In 1960 he received an offer of Associate Professorship from the Physics Department of the University of Minnesota, and in 1961 he moved to Minnesota where he stayed for the rest of his life. In 1963 he was promoted to full Professor. Gasiorowicz published over 100 papers on high-energy physics, and several well-known textbooks on the theory of elementary particles, quantum mechanics, and other subjects. Best known are Gasiorowicz’s contributions to quark models of hadrons, theory of glueballs, and QCD confinement. Gasiorowicz was one of the founding fathers of William I. Fine Theoretical Physics Institute. From 1979 to 1986 Gasiorowicz was Vice-President of the Aspen Center for Physics, Aspen, CO, and in 1987-89 the Acting Director of FTPI."},
    {"p_7", "Schroeder", "Thermal Physics", "10000","schroeder_thermalPhysics.jpg", "This text provides a balanced, well-organized treatment of thermodynamics and statistical mechanics, making thermal physics interesting and accessible to anyone who has completed a year of calculus-based introductory physics. Part I introduces essential concepts of thermodynamics and statistical mechanics from a unified view, applying concepts in a select number of illustrative examples. Parts II and III explore further applications of classical thermodynamics and statistical mechanics. Throughout, the emphasis is on real-world applications.", "Daniel V. Schroeder is a professor of physics at Wellesley College. He earned his Ph.D. in physics from Stanford University, where his research focused on theoretical studies of elementary particle physics and cosmology. After completing his doctorate, he worked as a researcher and educator at various institutions, developing expertise in computational methods and statistical mechanics. Schroeder is widely recognized for his clear and accessible teaching style, which has influenced generations of students. He is the author of An Introduction to Thermal Physics, a highly regarded textbook in the field, and co-author of Introduction to Electrodynamics: Problem Solutions Manual alongside David J. Griffiths. His academic interests include thermodynamics, statistical physics, computational simulations, and the pedagogy of physics education. Schroeder is also actively engaged in science communication and has contributed to initiatives aimed at improving undergraduate science curricula."}};

    private String bookId;
    private String author;
    private String title;
    private String price;
    private String imagePath;
    private String category;
    private List<String> keywords;

    public Book(String bookId, String author, String title, String price, String imagePath, String category, List<String> keywords) {
        this.bookId = bookId;
        this.author = author;
        this.title = title;
        this.price = price;
        this.imagePath = imagePath;
        this.category = category;
        this.keywords = keywords;
    }

    public String getBookId() {
        return bookId;
    }

    public String getAuthor() {
        return author;
    }

    public String getTitle() {
        return title;
    }

    public String getPrice() {
        return price;
    }

    public String getImagePath() {
        return imagePath;
    }

    public String getCategory() {
        return category;
    }

    public List<String> getKeywords() {
        return keywords;
    }

    public boolean matches(String query) {
        String lowerQuery = query.toLowerCase();
        if (title.toLowerCase().contains(lowerQuery)) return true;
        if (author.toLowerCase().contains(lowerQuery)) return true;
        if (category.toLowerCase().contains(lowerQuery)) return true;
        for (String keyword : keywords) {
            if (keyword.toLowerCase().contains(lowerQuery)) return true;
        }
        return false;
    }
}
